#!/bin/sh
. /etc/functions.sh
include /lib/config

config_load network
config_get proto wan proto

##check pptp vpn rule could be killed
/usr/sbin/ip rule del dev lan table vpn 2>/dev/null

[ -z "$6" ] || env -i ACTION="ifdown" INTERFACE="$6" DEVICE="$1" PROTO=ppp /sbin/hotplug-call "iface"

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" $@
	done
}
