#!/bin/sh
. /etc/functions.sh
include /lib/config

config_load network
config_get proto wan proto
##add pptp routing rule and route info in routing table vpn 
[ "$proto" == "pptp" ] && {
        /usr/sbin/ip rule del dev lan table vpn 2>/dev/null
	/usr/sbin/ip rule add dev lan table vpn 2>/dev/null
        /usr/sbin/ip route add default via $5 dev ppp0 table vpn 2>/dev/null
}


[ -z "$6" ] || env -i ACTION="ifup" INTERFACE="$6" DEVICE="$1" PROTO=ppp /sbin/hotplug-call "iface"

[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" $@
	done
}
