#
# (C) Copyright 2012 The Chromium Authors
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += ar7240_gpio.o
obj-y += cmd_zgpio.o
obj-y += ipq807x_gpio.o
obj-y += rt2880_gpio.o
obj-y += rt2880_gpio.o
obj-y += ruby_gpio.o
obj-y += zflash.o

