#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_PACKAGE                          144	/*Device.Services.X_ZYXEL_Package.i*/
#define RDM_OID_PACKAGE_INSTALL                  324	/*Device.Services.X_ZYXEL_Package_Install*/
#define RDM_OID_VOICE_SRV                        384	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       468	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1272	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1572	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1632	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1716	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1896	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          2892	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   3024	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4572	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4728	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   4836	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              5016	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              5124	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        5256	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5484	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5736	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  5964	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            6072	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      6156	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6360	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6732	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       6912	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   7284	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7560	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7668	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7776	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    7860	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        8016	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       8148	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9648	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 9804	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            10008	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               10260	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10416	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   11196	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       11808	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     11988	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12384	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12420	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12480	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 12660	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            12744	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 12924	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 12984	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 13068	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        13128	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   13188	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13464	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13524	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   14016	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14340	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_DEV_INFO                         14568	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          15108	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          15264	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                15396	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 15480	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              15564	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        15744	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            15804	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     16248	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               16332	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         16416	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            16548	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     16680	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_DEV_INFO_POWER_STAT              16836	/*Device.DeviceInfo.X_ZYXEL_PowerStatus*/
#define RDM_OID_MGMT_SRV                         16920	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                18876	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 19056	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                19188	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        19224	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  19332	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          19464	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 19572	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             19704	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             19956	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_GATEWAY_INFO                     20112	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             20220	/*Device.Time*/
#define RDM_OID_USR_INTF                         20880	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              21492	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              21624	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      21852	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              22008	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         22116	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      26112	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                26460	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             26952	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        27444	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         27528	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         28020	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             28104	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      28668	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   29184	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             29532	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          29712	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     29892	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           30072	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           30252	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      30432	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       30948	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   31032	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 31068	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   31296	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             31764	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       32064	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            32364	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  32664	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               32700	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         33120	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          33156	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              34056	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         34116	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      34464	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              34692	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         34752	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      35292	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     35784	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         35940	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   35976	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   36276	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              36576	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         36636	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      37200	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              37596	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      37728	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        38292	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      38712	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         39108	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      39432	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    39828	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 40128	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              40524	/*Device.USB*/
#define RDM_OID_USB_INTF                         40608	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    40908	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         41304	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     41532	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                41592	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            41820	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        42336	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        42492	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   42576	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_CELLULAR                         42708	/*Device.Cellular*/
#define RDM_OID_CELLULAR_INTERFACE               42816	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELLULAR_IFACE_U_S_I_M           43164	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELLULAR_ACCESS_POINT            43272	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_HPNA                             43500	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        43560	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     44244	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    44640	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          44700	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              45072	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        45300	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         45336	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  45612	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              45816	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     45924	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 46032	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  46668	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 46752	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             47052	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        47112	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     48012	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    48408	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            48516	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              48696	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              49140	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         49200	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      49764	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               50160	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        50316	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    50376	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 50796	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          51312	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              51516	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         51576	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      52116	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               52512	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            52812	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              52968	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         53076	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        53112	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             53292	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    53472	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       53532	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    55272	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        55524	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   56184	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                56580	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            56952	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     57972	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            58200	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      58644	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   58920	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  59172	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   59256	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                59436	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               59568	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           59628	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       59808	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WPS                              59940	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  60048	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          60156	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 60600	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   61044	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_BRIDGING                         61368	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      61644	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 61944	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              62412	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 62808	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             62940	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  63096	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              63924	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        64008	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  64956	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  64992	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   65124	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  65280	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   65364	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               65760	/*Device.IP*/
#define RDM_OID_IP_IFACE                         66012	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 67512	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 67764	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               68136	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    68580	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   68976	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          69132	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   69168	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 69612	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          69936	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  70068	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG                  70536	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             70956	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            71280	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         71796	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          72024	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IPSEC                            72348	/*Device.IPSec*/
#define RDM_OID_IPSEC_STAT                       72720	/*Device.IPSec.Stats*/
#define RDM_OID_IPSEC_FILTER                     73044	/*Device.IPSec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    73608	/*Device.IPSec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       74244	/*Device.IPSec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     74376	/*Device.IPSec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                74508	/*Device.IPSec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    74664	/*Device.IPSec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               75012	/*Device.IPSec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   75240	/*Device.IPSec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           75324	/*Device.IPSec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      75480	/*Device.IPSec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_GRE                              75756	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       75840	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  76476	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 76752	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            77052	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       77280	/*Device.GRE.Filter.i*/
#define RDM_OID_CAPT_PORTAL                      77532	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          77664	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   77724	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            77952	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            78468	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      78744	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             78852	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  79104	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         79188	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               79464	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      79548	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           79848	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  79932	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              80520	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           80652	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      80736	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          81036	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 81120	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              81468	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          82080	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          84204	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         84480	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      84804	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          85368	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     85908	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       86208	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     86388	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            86448	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       86532	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               87432	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               87492	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                87552	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              87852	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       88008	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   88116	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        88392	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    88500	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         88680	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          88716	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   88968	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              89148	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 89424	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 89580	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              90096	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 90420	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  90744	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           90924	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    90984	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  91452	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   91584	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       91740	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  91848	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      92700	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              92832	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           92964	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   93120	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       93204	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                93288	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     93468	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 93576	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           94020	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    94080	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                94524	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           94632	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       94764	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       94872	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  94956	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           95712	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   95892	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 96000	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       96108	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              96192	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_IEEE8021X                        96348	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             96408	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        96876	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      97176	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      97260	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             97344	/*Device.Users*/
#define RDM_OID_USRS_USR                         97404	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               97584	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           97644	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        97872	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             98028	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         98064	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    98388	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        98712	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               98820	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    99024	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                99228	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             99408	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        99588	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   99816	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         99900	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   100224	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   100476	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              100632	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  101676	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       101784	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 102132	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        102432	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EXEC_ENV               102540	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        103032	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              103404	/*Device.SoftwareModules.ExecutionUnit*/
#define RDM_OID_SW_MODULE_EXEC_UNIT_EXT          103944	/*Device.SoftwareModules.ExecutionUnit.Extensions*/
#define RDM_OID_FAULT_MGMT                       103980	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            104160	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         104316	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         104592	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       104868	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            105144	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          105420	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     105480	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              105948	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          105984	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         106356	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            106728	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    106956	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               107016	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    107220	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               107376	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               107724	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   107808	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           108036	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           108240	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      108444	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               108672	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   108804	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           108984	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           109164	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      109344	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        109524	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   109752	/*Device.BulkData.Profile.i*/
#define RDM_OID_BULK_DATA_PROF_PARAM             110124	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_ROM_CONVERT                      110184	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         110244	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     110520	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     110556	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   110784	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        110964	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   111024	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       111300	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       111792	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           112044	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     112152	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        112380	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            112464	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        112884	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       113112	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      113220	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_ZY_HOST_NAME_REPLACE             113352	/*Device.X_ZYXEL_EXT.HostNameReplace*/
#define RDM_OID_PPTP_CFG                         113412	/*Device.X_ZYXEL_EXT.X_ZYXEL_PPTP_Config*/
#define RDM_OID_EOGRE_CFG                        113712	/*Device.X_ZYXEL_EXT.X_ZYXEL_EoGRE_Config*/
#define RDM_OID_LAN_DEV                          113892	/*Device.X_ZYXEL_EXT.LANDevice.i*/
#define RDM_OID_EASY_MESH                        114000	/*Device.X_ZYXEL_EXT.EasyMesh*/
#define RDM_OID_ZY_IGMP                          114060	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          114552	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        114708	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           114816	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       115236	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    115344	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            115500	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    116328	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         116436	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            116544	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     116652	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     116808	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     116892	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   116976	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   117108	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   117192	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             117276	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        117336	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         117420	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            117720	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      117828	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         118104	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           118236	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  118344	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      118476	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   118536	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      118788	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_GPON_INFO                        119016	/*Device.X_ZYXEL_GPON_Info*/
#define RDM_OID_LOG_SETTING                      119220	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     119424	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     119532	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 119712	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      119844	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       119976	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 120156	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 120312	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            120372	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ACL                              120552	/*Device.X_ZYXEL_TR064.ACL*/
#define RDM_OID_CONTROL_POINT                    120588	/*Device.X_ZYXEL_TR064.ACL.CP.i*/
#define RDM_OID_ACTIONS                          120720	/*Device.X_ZYXEL_TR064.ACL.Actions.i*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                120828	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            121272	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        121428	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  122112	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_SAMBA                         122364	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     122472	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                122724	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 123120	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     123300	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     123624	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               123684	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       123816	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             123948	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              123984	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              124692	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              125160	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       125292	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         125400	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        125508	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               125640	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           125796	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             125880	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          126036	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           126120	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         126204	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             126240	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          126444	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            126600	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            126684	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           126840	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        127020	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         127080	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              127308	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         127368	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      127500	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            127560	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      127620	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   127680	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 127788	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 127872	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          128004	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             128112	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               128388	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_LANDING_PAGE                     128640	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       128724	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   129120	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    129276	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              129384	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_RESET_ADMIN                   129444	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_OI_WIZARD                        129504	/*Device.X_ZYXEL_OiWizard*/
#define RDM_OID_ZY_DATA_USAGE                    129708	/*Device.X_ZYXEL_DataUsage*/
#define RDM_OID_ZY_DATA_USAGE_LAN                129768	/*Device.X_ZYXEL_DataUsage.Lan.i*/
#define RDM_OID_ZY_DATA_USAGE_WAN                129876	/*Device.X_ZYXEL_DataUsage.Wan.i*/
#define RDM_OID_IPERF                            129984	/*Device.X_TELECOMITALIA_IT_Iperf*/
#define RDM_OID_ZLOG_CONFIG                      130116	/*Device.X_ZYXEL_Zlog_Setting*/
#define RDM_OID_ZLOG_CATEGORY                    130200	/*Device.X_ZYXEL_Zlog_Setting.ZlogCategory.i*/

#define RDM_OID_MAX                   130548     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
