#ifndef _ZHTTPD_RET
#define _ZHTTPD_RET

#include "zcfg_common.h"

static char *retStringGet[] = {
	"ZCFG_RET_OFFSET",
	"ZCFG_DELETE_REJECT",
	"ZCFG_REQUEST_REJECT",
	"ZCFG_REQUEST_POSTPONED",		/*request is postponed*/
	"ZCFG_INVALID_OBJECT",			/*invalid object name*/
	"ZCFG_INVALID_PARAM_VALUE",
	"ZCFG_INVALID_PARAM_VALUE_LENGTH",
	"ZCFG_INVALID_IMAGE",
	"ZCFG_INVALID_ARGUMENTS",
	"ZCFG_SET_READ_ONLY_PARAM",
	"ZCFG_EXCEED_MAX_INS_NUM",
	"ZCFG_INS_CREATE_ERR",
	"ZCFG_NOT_INSTANCE",
	"ZCFG_SET_ATTR_ERROR",
	"ZCFG_INVALID_FORMAT", 
	"ZCFG_NOT_FOUND",
	"ZCFG_NO_SUCH_OBJECT",			/*instance not exist*/
	"ZCFG_INTERNAL_ERROR",
	"ZCFG_NO_SUCH_PARAMETER",
	"ZCFG_ERROR_PARAMETER_TYPE",
	"ZCFG_INVALID_EID",
	"ZCFG_TIMEOUT",
	"ZCFG_SUCCESS",
	"ZCFG_SUCCESS_AND_NO_REPLY",
	"ZCFG_NO_MORE_INSTANCE",
	"ZCFG_EMPTY_OBJECT",
	"ZCFG_OBJECT_UPDATED",
	"ZCFG_TR98_DATA_MODEL"
};
#endif
