#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_VOICE_SRV                        144	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       228	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1032	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1332	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1392	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1476	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1656	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          2628	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   2760	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4284	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4440	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   4548	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              4728	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              4836	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        4968	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5196	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5448	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  5676	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            5784	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      5868	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6072	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6444	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       6624	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   6996	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7272	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7380	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7488	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    7572	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        7728	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       7860	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9360	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 9516	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            9720	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               9972	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10128	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   10908	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       11520	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     11700	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12072	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12108	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12168	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 12348	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            12432	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 12612	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 12672	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 12756	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        12816	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   12876	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13152	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13212	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   13704	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14028	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_DEV_INFO                         14256	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          14796	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          14952	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                15084	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 15168	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              15252	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        15432	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            15492	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     15936	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               16020	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         16104	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            16236	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     16368	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_DEV_INFO_POWER_STAT              16524	/*Device.DeviceInfo.X_ZYXEL_PowerStatus*/
#define RDM_OID_MGMT_SRV                         16608	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                18276	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 18456	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                18588	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        18624	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  18732	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          18864	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 18972	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             19104	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             19356	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_GATEWAY_INFO                     19512	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             19620	/*Device.Time*/
#define RDM_OID_USR_INTF                         20280	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              20868	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              21000	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      21228	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              21384	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         21492	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      25488	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                25836	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             26328	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        26820	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         26904	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         27396	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             27480	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      28044	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   28560	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             28908	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          29088	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     29268	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           29448	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           29628	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      29808	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       30324	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   30408	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 30444	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   30672	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             31140	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       31440	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            31740	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  32040	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               32076	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         32496	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          32532	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              33432	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         33492	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      33840	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              34068	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         34128	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      34668	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     35160	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         35316	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   35352	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   35652	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              35952	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         36012	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      36576	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              36972	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      37104	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        37668	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      38088	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         38484	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      38808	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    39204	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 39504	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              39900	/*Device.USB*/
#define RDM_OID_USB_INTF                         39984	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    40284	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         40680	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     40908	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                40968	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            41196	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        41712	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        41820	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   41904	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_CELLULAR                         42036	/*Device.Cellular*/
#define RDM_OID_CELLULAR_INTERFACE               42144	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELLULAR_IFACE_U_S_I_M           42492	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELLULAR_ACCESS_POINT            42600	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_HPNA                             42828	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        42888	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     43572	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    43968	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          44028	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              44400	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        44628	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         44664	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  44940	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              45144	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     45252	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 45360	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  45996	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 46080	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             46380	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        46440	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     47340	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    47736	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            47844	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              48024	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              48468	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         48528	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      49092	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               49488	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        49644	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    49704	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 50124	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          50640	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              50844	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         50904	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      51444	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               51840	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            52140	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              52296	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         52404	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        52440	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             52620	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    52776	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       52836	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    54504	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        54756	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   55416	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                55812	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            56184	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     57204	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            57432	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      57828	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   58104	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  58356	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   58440	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                58620	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               58752	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           58812	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       58992	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WPS                              59124	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  59232	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          59340	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 59784	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   60228	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_BRIDGING                         60552	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      60828	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 61128	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              61596	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 61992	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             62124	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  62280	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              63108	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        63192	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  64140	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  64176	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   64308	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  64464	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   64548	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               64944	/*Device.IP*/
#define RDM_OID_IP_IFACE                         65196	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 66696	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 66948	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               67320	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    67764	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   68160	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          68316	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   68352	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 68796	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          69120	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  69252	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG                  69720	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             70140	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            70464	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         70980	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          71208	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IPSEC                            71532	/*Device.IPSec*/
#define RDM_OID_IPSEC_STAT                       71904	/*Device.IPSec.Stats*/
#define RDM_OID_IPSEC_FILTER                     72228	/*Device.IPSec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    72792	/*Device.IPSec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       73428	/*Device.IPSec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     73560	/*Device.IPSec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                73692	/*Device.IPSec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    73848	/*Device.IPSec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               74196	/*Device.IPSec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   74424	/*Device.IPSec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           74508	/*Device.IPSec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      74664	/*Device.IPSec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_GRE                              74940	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       75024	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  75324	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 75552	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            75852	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       76080	/*Device.GRE.Filter.i*/
#define RDM_OID_CAPT_PORTAL                      76332	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          76464	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   76524	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            76752	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            77268	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      77544	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             77652	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  77904	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         77988	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               78240	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      78324	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           78624	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  78708	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              79296	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           79428	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      79512	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          79812	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 79896	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              80244	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          80856	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          82980	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         83256	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      83580	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          84144	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     84684	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       84984	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     85164	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            85224	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       85308	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               86160	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               86220	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                86280	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              86580	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       86736	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   86844	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        87120	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    87228	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         87408	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          87444	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   87696	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              87876	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 88152	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 88308	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              88824	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 89124	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  89424	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           89604	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    89664	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  90132	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   90264	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       90420	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  90528	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      91380	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              91512	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           91644	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   91800	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       91884	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                91968	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     92148	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 92256	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           92700	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    92760	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                93204	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           93312	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       93444	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       93552	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  93636	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           94392	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   94572	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 94680	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       94788	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              94872	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_IEEE8021X                        95028	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             95088	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        95556	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      95856	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      95940	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             96024	/*Device.Users*/
#define RDM_OID_USRS_USR                         96084	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               96264	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           96324	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        96552	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             96708	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         96744	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    97068	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        97392	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               97500	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    97704	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                97908	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             98088	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        98268	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   98496	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         98580	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   98904	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   99156	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              99312	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  100356	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       100464	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 100812	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        101112	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EXEC_ENV               101220	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        101712	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              102084	/*Device.SoftwareModules.ExecutionUnit*/
#define RDM_OID_SW_MODULE_EXEC_UNIT_EXT          102624	/*Device.SoftwareModules.ExecutionUnit.Extensions*/
#define RDM_OID_FAULT_MGMT                       102660	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            102840	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         102996	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         103272	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       103548	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            103824	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          104100	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     104160	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              104628	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          104664	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         105036	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            105408	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    105636	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               105696	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    105900	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               106056	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               106404	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   106488	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           106716	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           106920	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      107124	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               107352	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   107484	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           107664	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           107844	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      108024	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        108204	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   108432	/*Device.BulkData.Profile.i*/
#define RDM_OID_BULK_DATA_PROF_PARAM             108804	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_ROM_CONVERT                      108864	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         108924	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     109200	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     109236	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   109464	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        109644	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   109704	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       109956	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       110448	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           110700	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     110808	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        111036	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            111120	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        111540	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       111768	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      111876	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_PPTP_CFG                         112008	/*Device.X_ZYXEL_EXT.X_ZYXEL_PPTP_Config*/
#define RDM_OID_EOGRE_CFG                        112308	/*Device.X_ZYXEL_EXT.X_ZYXEL_EoGRE_Config*/
#define RDM_OID_LAN_DEV                          112488	/*Device.X_ZYXEL_EXT.LANDevice.i*/
#define RDM_OID_ZY_IGMP                          112596	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          113088	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        113244	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           113352	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       113772	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    113880	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            114036	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    114768	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         114876	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            114984	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     115068	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     115224	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     115308	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   115392	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   115524	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   115608	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             115692	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        115752	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         115836	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            116112	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      116220	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         116496	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           116628	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  116736	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      116868	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   116928	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      117180	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_GPON_INFO                        117384	/*Device.X_ZYXEL_GPON_Info*/
#define RDM_OID_LOG_SETTING                      117588	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     117792	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     117900	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 118080	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      118212	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       118344	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 118524	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 118680	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            118740	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                118800	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            119196	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        119352	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  120036	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_SAMBA                         120264	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     120348	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                120600	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 120996	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     121176	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     121404	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               121464	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       121596	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             121728	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              121764	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              122472	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              122940	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       123072	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         123180	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        123288	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               123420	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           123576	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             123660	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          123816	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           123900	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         123984	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             124020	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          124224	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            124380	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            124464	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           124620	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        124800	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         124860	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              125088	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         125148	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      125280	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            125340	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      125400	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   125460	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 125544	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 125628	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          125736	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             125820	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               126048	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_LANDING_PAGE                     126300	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       126384	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   126780	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    126936	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              127044	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_RESET_ADMIN                   127104	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_OI_WIZARD                        127164	/*Device.X_ZYXEL_OiWizard*/

#define RDM_OID_MAX                   127368     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
